### ISSUE TITLE
Unhandled error: undefined

### ISSUE THREAD

**Issue by danielloera** [mymonero/mymonero-android-js#22]
I went to the settings menu and changed the currency. Now every time I open the app [I see this error.](https://imgur.com/a/bj0p3WF) I am now unable to change the currency at all.

**Comment by karlbuys** [comment]
Hi @danielloera 

We released v1.1.21 yesterday, which fixes the "undefined" error and allows the default currency to be selected and saved.

Tests on our devices show that this has resolved the issue.

Thank you for going the extra mile by creating a report here

I'm going to close this ticket, but if you continue to experience the issue, please let me know and we'll re-open this

**Comment by danielloera** [comment]
Thanks for the prompt fix
