### ISSUE TITLE
Use /bin/sh instead of bash in scripts

### ISSUE THREAD

**Issue by emanuelb** [mymonero/mymonero-android-js#27]
The scripts in this repo use `#!/usr/bin/env bash` while the content of the scripts doesn't use anything bash specific, thus need to be replaced to `#!/bin/sh` which avoid bash as required dependency (will use the default shell instead)
The scripts files are:
> /bin/update_submodules
/bin/build_and_pack__browser
/bin/__webpack_browser__dev
/bin/__webpack_browser__prod
/bin/_build_browser_prod
/bin/_build_browser_dev
/bin/start_dev_browser
/bin/lint__local_modules

**Comment by devinpearson** [comment]
Thanks for the suggestion. We have over the last few months been moving to use a unified repo for both IOS and Android and no longer use these scripts. you can find the new repo here: https://github.com/mymonero/mymonero-mobile.
