### ISSUE TITLE
QR Code works on desktop, not on mobile app

### ISSUE THREAD

**Issue by akvadrako** [mymonero/mymonero-android-js#41]
I am trying to use the MyMonero Android app to send using a QR Code. The code works on the desktop (Linux) app, but I get an error on my phone:

> Unable to use the result of decoding that QR Code: No Monero request info.

The code is here:

![image](https://user-images.githubusercontent.com/184545/118783454-5e7cbf80-b88f-11eb-8ed2-95f0c6d97873.png)

This is version 1.1.21 from the Play store on Android 11.

**Comment by karlbuys** [comment]
Hi akvadrako

I've successfully managed to import the QR code on our test device. Choose file and use camera both worth on the test device when running Monero 1.1.21 and Android 10.

Could you please let me know what version of Android, and what make and model of device you used when you encountered the problem?

**Comment by akvadrako** [comment]
I'm not getting the error today, though I haven't changed anything except a newer Android patch. This is on a Pixel 4a with Android 11 (RQ2A.210505.002)

**Comment by karlbuys** [comment]
I'm glad to hear the issue is resolved on your side. I'm going to mark the issue as solved, but if you do experience it again, please let us know
