### ISSUE TITLE
MyMonero for Android defaults to port 8443/tcp even when protocol http or https is specified

### ISSUE THREAD

**Issue by sethforprivacy** [mymonero/mymonero-android-js#84]
### Description

When connecting to a custom LWS, MyMonero ignores default ports for protocols (http: and https:, specifically) and attempts to connect to port 8443/tcp, making LWS using a normal HTTP/HTTPS port not work and give "LOGIN ERROR" unless the correct port for that protocol is specified (i.e. https://lws.sethforprivacy.com:443).

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Set custom server address to https://lws.sethforprivacy.com
2. MyMonero gives "LOGIN ERROR" and fails to sync
3. Specify port, i.e. https://lws.sethforprivacy.com:443
4. MyMonero properly connects and syncs

**Expected behavior:**

MyMonero should respect and use the default port when protocol is given, i.e. 80/tcp for http, 443/tcp for https.

Another approach could be trying 8443 by default and falling back to 80/443 if 8443 fails.

**Actual behavior:**

MyMonero fails to connect to custom LWS unless specifying the port.

### Versions

- Mark Text version: 1.2.1, both Play Store and Github APKs
- Operating system: CalyxOS 3.2.0 (Android 12)

**Comment by devinpearson** [comment]
Thanks for bringing this up. I will take a look at this as well. our current HTTP library that's using the apps currently adds https:// to the value entered in the custom URL box and adds a / at the end.  I'll let it take the full domain name

**Comment by sethforprivacy** [comment]
> Thanks for bringing this up. I will take a look at this as well. our current HTTP library that's using the apps currently adds https:// to the value entered in the custom URL box and adds a / at the end. I'll let it take the full domain name

I forgot that this behavior also happens when you use bare URL -- it assumes 8443 instead of 80 as would be normal in other apps/browsers.

That's definitely more understandable behavior, but important to call out in the app if you put bare URL and it cannot connect, can prompt the user to try :80, :443, or (once fixed) http: or https:.

**Comment by devinpearson** [comment]
Most of the apps should no longer be using 8443 I've pushed for them to use default port 80 as we have had a number of users where their network blocks port 8443.

**Comment by sethforprivacy** [comment]
The MyMonero Android app defaults to :8443 if you don't specify port is the issue.

When designing LWS, I would assume (and hope) https: and 443 are the default (as they will be in my future guides around using monero-lws w/ Traefik).

That's one of the things that makes it important that MyMonero doesn't assume :8443 incorrectly, even when the protocol (https:) is specified which should default to :443 by proper standards.

**Comment by devinpearson** [comment]
It will have the defaults in the next release. We have some changes that will are waiting to go out. we are expecting that it will also be F-Droid compatible and we can submit it there

**Comment by sethforprivacy** [comment]
> It will have the defaults in the next release. We have some changes that will are waiting to go out. we are expecting that it will also be F-Droid compatible and we can submit it there

Would be *great* to have it from F-Droid as well! Thanks 😄

**Comment by devinpearson** [comment]
The port is no longer hardcoded. with the latest release you can now specify it or leave it out and it will use 443 if the url is https.

You can find the release here: https://github.com/mymonero/mymonero-mobile

The ios app will now be using the same codebase as the android app hence the renaming of the repo. we have also updated the underlying capacitor which has reduced the size of the app.

**Comment by sethforprivacy** [comment]
Confirmed this is resolved in v1.2.6+.
